-- MIGRACIÓN PARA NUMERACIÓN CORRELATIVA EN GASTOS Y TURNOS
-- Ejecutar en el SQL Editor de Supabase

BEGIN;

-- 1. Añadir número correlativo a Gastos
ALTER TABLE public.expenses 
ADD COLUMN IF NOT EXISTS expense_number BIGINT GENERATED BY DEFAULT AS IDENTITY;

-- 2. Asegurar que la secuencia comience desde el último registro si ya hay datos
-- SELECT setval(pg_get_serial_sequence('public.expenses', 'expense_number'), coalesce(max(expense_number), 0) + 1, false) FROM public.expenses;

-- 3. Añadir número correlativo a Turnos (Shifts)
ALTER TABLE public.shifts 
ADD COLUMN IF NOT EXISTS shift_number BIGINT GENERATED BY DEFAULT AS IDENTITY;

-- 4. Actualizar índices para búsquedas por número
CREATE INDEX IF NOT EXISTS idx_expenses_number ON public.expenses(expense_number);
CREATE INDEX IF NOT EXISTS idx_shifts_number ON public.shifts(shift_number);

COMMIT;
